apiVersion: v1
kind: Service 
metadata:
  name: {{ include "gt-frontend.fullname" .}}-service
  labels:
    app: gt-frontend-app
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 80 }}
  selector:
    app: gt-frontend-app