apiVersion: v1
kind: Service 
metadata:
  name: {{ include "gt-pdf.fullname" . }}-service
  labels:
    app: gt-pdf-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.pdfservice.port }}
    targetPort: {{ .Values.pdfservice.targetPort }}
  selector:
    app: gt-pdf-app